### ISSUE TITLE
Add new languages for emails

### ISSUE THREAD

**Issue by AntoineMarnat** [c2corg/v6_api#1477]
Here : https://github.com/c2corg/v6_api/tree/master/c2corg_api/emails/i18n
there is neither sl nor zh. 

See https://forum.camptocamp.org/t/ameliorer-le-multilingue-avec-discourse/216785/4

Maybe this should be linked to Transifex ?

**Comment by brunobesson** [comment]
We could to some job, but there isn't that much content.
At least, we could ask @hemind and Borut to provide the translations?

**Comment by hemind** [comment]
> 

I am happy to translate emails to Chinese.

**Comment by brunobesson** [comment]
> I am happy to translate emails to Chinese.

🥳 
Then see this link: [/c2corg_api/emails/i18n](https://github.com/c2corg/v6_api/tree/master/c2corg_api/emails/i18n). There is a missing `zh` folder which should contain the same file as for other languages, but translated into chinese. There is usually one file for the mail title, on for the body. Inside, `%s` are tags that are replaced when processing the email. It usually correspond to an email, a link, etc. It should be pretty easy to guesse what it is.
Could you provide translations this way? Let me now if you need more help.

**Comment by BorutK** [comment]
Hello everyone!

Antoine sent out the messages to translate into Slovenian. For now, I'll send him translations per PM on c2c. 

Borut

**Comment by BorutK** [comment]
Hello Bruno!

Here are the translations… and thanks again for your time!

----

>Hello
>
>To activate your new email click on %s
>
>Thank you very much
>
>The Camptocamp.org team


Doberdan

Za aktiviranje vašega novega e-poštnega naslova kliknite %s

Hvala lepa

Ekipa Camptocamp.org

----

>Email change on Camptocamp.org


Sprememba e-pošte na Camptocamp.org

----

>Hello
>
>To change your password click on %s
>
>Your username is « %s »
>
>Please note the username is case-sensitive.
>
>Thank you very much
>
>The Camptocamp.org team


Doberdan

Za spremembo gesla kliknite %s

Vaše uporabniško ime je « %s »

Upoštevajte, da uporabniško ime razlikuje med velikimi in malimi črkami.

Hvala lepa

Ekipa Camptocamp.org

----

>Password change on Camptocamp.org


Sprememba gesla na Camptocamp.org

----

>Hello
>
>To activate your account click on %s
>
>Thank you very much
>
>The Camptocamp.org team


Doberdan

Za aktiviranje računa kliknite %s

Hvala lepa

Ekipa Camptocamp.org

----

>Registration on Camptocamp.org


Registracija na Camptocamp.org

----

Poslano iz programa Pošta<https://go.microsoft.com/fwlink/?LinkId=550986> za Windows

Od: Bruno ***@***.***>
Poslano: torek, 10. januar 2023 11:15
Za: ***@***.***>
Kp: ***@***.***>; ***@***.***>
Zadeva: Re: [c2corg/v6_api] Add new languages for emails (Issue #1477)


You could send it to me instead, or in addition to, otherwise it's fine.

Sorry @BorutK<https://github.com/BorutK> I didn't remember your GitHub account, that's why you weren't mentionned properly 😭

**Comment by hemind** [comment]
> Hello
> 
> To activate your new email click on %s
> 
> Thank you very much
> 
> The [Camptocamp.org](http://camptocamp.org/) team

你好

激活你的新邮箱请点击 %s

非常感谢

[Camptocamp.org](http://camptocamp.org/) 团队

> Email change on [Camptocamp.org](http://camptocamp.org/)

更改你的 [Camptocamp.org](http://camptocamp.org/) 账户邮箱

> Hello
> 
> To change your password click on %s
> 
> Your username is « %s »
> 
> Please note the username is case-sensitive.
> 
> Thank you very much
> 
> The [Camptocamp.org](http://camptocamp.org/) team

你好

更改你的密码请点击 %s

你的用户名是 « %s »

请注意用户名区分大小写

非常感谢

[Camptocamp.org](http://camptocamp.org/) 团队

> Password change on [Camptocamp.org](http://camptocamp.org/)

更改你的 [Camptocamp.org](http://camptocamp.org/) 账户密码

> Hello
> 
> To activate your account click on %s
> 
> Thank you very much
> 
> The [Camptocamp.org](http://camptocamp.org/) team

你好

激活你的账户请点击 %s

非常感谢

[Camptocamp.org](http://camptocamp.org/) 团队

> Registration on [Camptocamp.org](http://camptocamp.org/)

注册 [Camptocamp.org](http://camptocamp.org/) 账户

**Comment by AntoineMarnat** [comment]
I created the two pull requests !

**Comment by BorutK** [comment]
👍
________________________________
