### ISSUE TITLE
Limit between which document types associations can be created

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_api#157]
Currently the association web-service allows to create association between all kind of documents. The following combinations should only be allowed: https://github.com/c2corg/camptocamp.org/blob/master/data/sql/tables/db_associations.sql#L14-L73

To consider: Should two-way links be allowed (e.g. R1 -> R2 and R2 -> R1 between two routes)?

**Comment by tsauerwein** [comment]
Or: Only allow associations between the following types: https://github.com/c2corg/camptocamp.org/blob/master/data/sql/tables/db_associations.sql#L14-L73

**Comment by asaunier** [comment]
Shouldn't we use the other approach? Instead of blocking some kinds of associations we should only allow some. For instance:
* WP
  * WP
  * routes
  * images
  * ...
* routes
 * WP
 * routes
 * images
 * outings
 * ...
* outings
 * routes
 * images
 * users
 * ...

I don't list geoassociations (areas) and maps since they are computed automatically.

**Comment by asaunier** [comment]
> Only allow associations between the following types:

Voila :)
