### ISSUE TITLE
conditions_levels -> object

### ISSUE THREAD

**Issue by ginold** [c2corg/v6_api#266]
would it be possible to return outing's contidion_levels as an array and not as a string?
In order to make it work, i have to json.parse it before showing and json.stringify before sending back to the api.

And to let accept it as empty/null. As from now, I receive an error `[<colander.null>] is not a string: {'conditions_levels': ''}`

**Comment by tsauerwein** [comment]
To accept the condition levels as array, I would have to define a mapping type for the condition levels. Right now, you can store anything in the `conditions_levels` field (even serialized PHP objects), I am not sure if we want to be more strict?

**Comment by ginold** [comment]
It is still impossible to send empty conditions_levels without error. @tsauerwein could you please check it and make it possible accept empty conditions_levels if not filled?

**Comment by tsauerwein** [comment]
What are you sending and what error do you get?

**Comment by ginold** [comment]
Same as above. I need to send a string, or serialize an object that looks like `{'conditions_levels': : {xxx}, {yyy} }`, if it's not I will get `[<colander.null>] is not a string: {'conditions_levels': ''}`. So for now I send an empty string so it passes...

**Comment by tsauerwein** [comment]
I see three options:

1. On the client-side, we convert `conditions_levels` from a string to an object when receiving a document, and convert from an object to a string when sending a document. Similar to what is already done for the geometry.
2. On the server side: Like option 1 convert between JSON objects and strings, but on the server side.
3. Also on the server side: Validate what is sent as condition levels value, to be sure that all entries have the same schema. The following would have to be done:
 * Create a schema for conditions levels.
 * Verify that all migrated outings have a valid value for `conditions_levels`.
 * Adapt the views to do the validation and also convert between object and string.

Option 3 would be the best, but it is more an *extra* issue. So, I tend to option 1 because something similar is already done for geometries.
