### ISSUE TITLE
Missing attributes for WP

### ISSUE THREAD

**Issue by celinestern** [c2corg/v6_api#316]
See https://docs.google.com/spreadsheets/d/1Q_fl7UQKPMgzlnk5tvAGqrmesrwfA5gges8p25XLes8/edit#gid=1502780869 ranks 52 and 53

**Comment by asaunier** [comment]
A few comment:

* "review" is not a final interface (might be replaced), so it's no use "reviewing" it :)
* "lac" > "longueur": for me we already have too many attributes and this one is not a critical one, I have chosen to remove it.
* "site de couenne / bloc" (the name is no longer relevant since it could also be a multi-pitch site) > "Type de site: single/multi pas défini dans CC" => I don't remember where it comes from, but this is relevant to distinguish single/multi-pitch sites etc.
* "SAE" > "altitude" / "cartographie" / "orientations" / "enfants" / "meilleures périodes" / "pluie" / "types de rocher" => who needs such info for an indoor climbing gym? => this is not a mistake if those attributes are not shown.
* "bivouac" / "camp de base" > "Manque: nbre de places (apparaît que dans review), gardiennage, matelas, période de gardiennage" => we don't need those attributes for such waypoint. If really needed, they may be added to the description field.

**Comment by celinestern** [comment]
I agree with your comments. It was just different from CC and I notice them in this way.
Just for SAE, there are few one outdoor. How do we class them, in couenne with resine type of rock?

**Comment by asaunier** [comment]
> for SAE, there are few one outdoor.

They could be treated as "outdoor climbing sites" I think.

**Comment by fjacon** [comment]
@stef74 I think this can be closed

**Comment by celinestern** [comment]
Ok for me, you can close
