### ISSUE TITLE
Consistent results attributes in advanced search/simple search/association requests

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#348]
Results from various services such as the advanced search, the simple search or the list of associated documents are displayed in the UI using cards. For a given document type, a shared card partial is used.

Problem: all services do not return the same sets of attributes and some attributes are cannot be displayed in the cards. See for instance https://github.com/c2corg/v6_ui/pull/512#issue-166835614

It would be more consistent to have the same set of attributes for a given type of results, whatever the service used (with the adapted extern definition).

Probably also related (duplicate?) to https://github.com/c2corg/v6_api/issues/300

**Comment by tsauerwein** [comment]
See also https://github.com/c2corg/v6_api/issues/192

**Comment by fjacon** [comment]
What is the priority of this ?

**Comment by asaunier** [comment]
Quite high, else the cards in a document detail view page (associated documents) are not provided all the attributes they should display.

Compare for instance the list of route cards
* in the advanced search: http://c2corgv6.demo-camptocamp.com/routes?w=104251&bbox=-935508%2C3369261%2C1735507%2C7830738
* in a WP page: http://c2corgv6.demo-camptocamp.com/waypoints/104251/fr (some attributes are missing)

**Comment by tsauerwein** [comment]
I thought about this, I was a bit hesitant because I wanted to keep the results for the simple search as slim as possible.

But I think it is a good idea to use the same schema for the simple search, the advanced search and the associations. This makes it possible to use the same cache for the different API endpoints, it will simplify the code and you only have one place to configure the included attributes.

And I think it still makes sense to have a simple search and an advanced search. The simple search allows to search for multiple document types at the same time, while the advanced search is only for a single one. The simple search only searches in document titles, while the advanced search also scans the full document summary and description.
