### ISSUE TITLE
image.'has_svg' property 

### ISSUE THREAD

**Issue by ginold** [c2corg/v6_api#357]
Apparently this property is no longer needed and should be removed from the API as well as from Commons.
Any objections?

**Comment by asaunier** [comment]
In v5, I think ``has_svg`` is used to figure out if the current image was converted from an SVG source. A "view SVG source" is then displayed in the image page. For instance: http://www.camptocamp.org/images/208579/fr/face-n-des-grandes-jorasses-quelques-itineraires

In v6, we can display SVG images directly, without converting them to JPEG first. So probably we could handle SVG file the same way than JPEG, PNG or GIF and get rid of this ``has_svg`` attribute.
What about resized images? Is it possible to resize an SVG? That may sound silly since a vector file can easily be displayed at various size but generally our SVG embed a JPEG file on which drawings are made (see example above) => we should probably resize the embedded image. If possible...

**Comment by asaunier** [comment]
Is this ``has_svg`` attribute used in the UI or somewhere else?

It seems not:
* UI: https://github.com/c2corg/v6_ui/search?utf8=%E2%9C%93&q=has_svg
* API: https://github.com/c2corg/v6_api/search?utf8=%E2%9C%93&q=has_svg
* Common: https://github.com/c2corg/v6_common/search?utf8=%E2%9C%93&q=has_svg
* Images: https://github.com/c2corg/v6_images/search?utf8=%E2%9C%93&q=has_svg

@ginold @arnaud-morvan could you confirm?

If no longer we can remove it from API and Common. Let me know, I can do it.

**Comment by ginold** [comment]
only in common. I think you can remove it.
