### ISSUE TITLE
Field "pedestrian_access" of V5 huts is not migrated

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_api#466]
The field "pedestrian_access" of V5 huts is not migrated.
In V6, this field doesn't exist anymore.
It must be moved at the end of the description field, after the sub title : 
```## Accès pédestre```

**Comment by fbunoz** [comment]
> I fully agree with your comment Alex. I would remove this field from the list, it is totally confusing.

There is no proeminence data base on line, only some excel sheet downloadable. We have a good summit database. It is useful to use this database to make a proeminence database.

**Comment by asaunier** [comment]
> The field "pedestrian_access" of V5 huts is not migrated.

It is. Migrated to attribute "access" in v6:
https://github.com/c2corg/v6_api/blob/master/c2corg_api/scripts/migration/documents/waypoints/huts.py#L94

> It must be moved at the end of the description field, after the sub title "Accès pédestre"

Not that simple because this title must change depending on the document language.

There's something like that for climbing sites: https://github.com/c2corg/v6_api/blob/master/c2corg_api/scripts/migration/documents/waypoints/sites.py#L144-L210

but that's again more work...

**Comment by fbunoz** [comment]
> It is. Migrated to attribute "access" in v6:

Ok. We can have the V5 access field migrated into the V6 access field.
But in this case, the V6 access field must be shown in the WP document and in the edit form for the hut type.

**Comment by asaunier** [comment]
Moved to https://github.com/c2corg/v6_ui/issues/791#issuecomment-258195362
Closing.
