### ISSUE TITLE
Improve simple search accuracy

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_api#557]
Reported in https://github.com/c2corg/v6_ui/issues/351#issuecomment-247276509:

>  ... but there is still a problem when searching for "dent de barme" for example: corresponding results are not displayed first:

![image100](https://cloud.githubusercontent.com/assets/20488365/18544434/da15dda4-7b34-11e6-89fa-b8fa61d848b8.png)

**Comment by asaunier** [comment]
Another example that the simple search / association tool behaviour is not satisfaying, making it hard to use:

<img width="586" alt="capture d ecran 2017-02-27 a 15 52 33" src="https://cloud.githubusercontent.com/assets/1192331/23366140/eb5c101c-fd05-11e6-980c-89da5fde495f.png">

Typing "Bénévent face NW", I expect the results to contain all 3 words. Instead of that I get results with absolutely no connection with "Bénévent". For instance "Bionnassay face NW" => as if the words were used as OR clauses instead of AND clauses.

**Comment by brunobesson** [comment]
Another example: "gollachon" returns nothing while "golachon" exists in the database (well, that was the case until I created "Col du Gollachon" in prod - still valid on demo).

This is not related to an AND or OR clause, but I find it strange that such spelling errors are not accepted.
