### ISSUE TITLE
API is very slow if there is no filter

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/v6_api#663]
It's not always the case, I would say 10%, but when it happens, the API is very slow if no filter is used.

To reproduce, simply go here https://www.camptocamp.org/outings, and unselect "filter on map" (which is checked by default, and so, request is filtered).

You will see that filtered request is quite instant, but the non-filtered one can take up to 20 seconds.

**Comment by tsauerwein** [comment]
Good observation!

If no filters are given, the documents are [directly loaded from the database](https://github.com/c2corg/v6_api/blob/a300ced/c2corg_api/views/document.py#L82). For outings, the documents are [ordered](https://github.com/c2corg/v6_api/blob/5fa6347/c2corg_api/views/document_listings.py#L37) by `date_end` and the document id. Currently there is no index for this kind of query, this should explain the bad performance.

**Comment by cbeauchesne** [comment]
Can we consider that as a bug? Maybe a dirty fix could be a fake filter that always returns TRUE?, and thus use optimized code?

**Comment by asaunier** [comment]
> If no filters are given, the documents are directly loaded from the database. For outings, the documents are ordered by date_end and the document id. Currently there is no index for this kind of query, this should explain the bad performance.

@tsauerwein Thanks for the hint!

With PR #664 I suggest an Alembic script that adds an index on outing's ``date_end`` attribute.
Since we use Alembic for the DB creation as well, I guess it is not needed to explicitely define the index as in http://docs.sqlalchemy.org/en/latest/core/constraints.html#indexes ?

I have also find this post http://stackoverflow.com/a/40321047 saying that defining the primary key as (``document_id``, ``date_end``) should be 
> significantly (2-4 times) faster then an index on a date column

On the other hand the contributor says later that
>  an ordinary index significantly improves performance and should be sufficient

**Comment by cbeauchesne** [comment]
Seems not to happen anymore
