### ISSUE TITLE
Do not return protected or redirected documents

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_api#73]
Check the properties `protected` and `redirects_to` (which also should be a FK)

**Comment by asaunier** [comment]
Actually they should be returned by the API but clealy identified as protected or merged/redirected so that the UI adapts the presentation. For merged/redirected we probably need to make a 301 redirection? in v5, no redirection is done, the page is simply marked as "merged with doc ..." and all associations are skipped/removed.

**Comment by tsauerwein** [comment]
How should protected documents be handled?

- GET: return the document with all data?
- PUT: block unless moderator?
- show in list views?
- show in associations?
- index in ES?

**Comment by asaunier** [comment]
Protected documents are only documents that cannot be edited unless deprotected first by a moderator. Only moderators may protect/deprotect a document.

> GET: return the document with all data?

yes

> PUT: block unless moderator?

In v5, no one can edit unless a moderator deprotect the document. We could say that moderators are allowed to edit protected documents without deprotecting them first.

It would probably be a good idea to show an error when opening the editing form of a protected document.

> show in list views?

yes

> show in associations?

yes

> index in ES?

yes
