### ISSUE TITLE
Locales in listings?

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_api#83]
When requesting a single document in a specific culture, you will get the document only with that culture or 404 if there is no translation of the document for the culture.

But how should we do it for listings? Currently all locales are returned for the documents. But is that necessary? Should we maybe only return a *preferred* locale for each document? And if the *preferred* locale is not available use a different locale?

**Comment by asaunier** [comment]
Listed documents should be displayed (name + URL) using the current interface locale if possible. If some documents are not available in the interface locale:
* if only one culture => display this culture
* if several culture => in v5 every user may specify the order of his preferred languages (in the user settings) => thoses preferences are used to figure out what culture to use for those documents. I don't remember how it works for non-authenticated users, perhaps there's a list of hard-coded lang pref order?

The latter mechanism is perhaps a bit complicated. In addition since the UI knows nothing about the user (at least as for now), it cannot adapt the cultures when generating (in python) the documents lists.  We somehow have the same issue when making list requests to the API (even though we could pass cultures prefs as argument).

Perhaps we could simplify this behaviour and decide once for all the order of cultures to use. For instance fr>en>it>de>es>ca>eu? (based upon a rough guess of the cultures usage in v5)

**Comment by tsauerwein** [comment]
Ok, so I would propose to add the paramter `?l=..` to the listing and search services. This will be the *preferred* language. If a translation in this language is not available, a different translation will be used (based on the priority "fr>en>it>de>es>ca>eu").

**Comment by asaunier** [comment]
:+1:

**Comment by asaunier** [comment]
Mmmm, I wonder how we will do in the page lists: in the UI server side if we don't know the interface language we cannot add a ``?l=`` parameter to the the request to the API...

**Comment by tsauerwein** [comment]
For unauthenticated users you could to it the same way as on the client-side and use the browser language preferences ([Accept-Language](https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation#The_Accept-Language_header)).

But for authenticated users... maybe set the language on a cookie when logging in?

**Comment by tsauerwein** [comment]
> But for authenticated users... maybe set the language on a cookie when logging in?

And this cookie should also be set when an unauthenticated user selects a different interface language.

**Comment by asaunier** [comment]
As for now we return all locale versions (only a few attributes though). In the UI we then display a link towards each locale version (with the matching name).

If it doesn't hurt the perfs too much, I wonder if it would not be the simplest solution => no need to choose using a complex algorithm that might not fit the user's desire, the user can choose himself the version he wants to see. Perhaps that OK like this?

**Comment by asaunier** [comment]
That might also be better for search engines, making sure that all locale versions are actually accessible.

**Comment by tsauerwein** [comment]
> That might also be better for search engines, making sure that all locale versions are actually accessible.

The other translations are also accessible from the detail page.

> As for now we return all locale versions (only a few attributes though). In the UI we then display a link towards each locale version (with the matching name).

I am worried that this will take up too much space in the UI.

**Comment by tsauerwein** [comment]
> I am worried that this will take up too much space in the UI. 

At least for the auto-complete I can only display one locale. I am using the method that we mentioned above to select the "best" locale:
https://github.com/c2corg/v6_ui/blob/search-control/c2corg_ui/static/js/utils.js#L38

**Comment by tsauerwein** [comment]
Fixed with https://github.com/c2corg/v6_api/pull/115
