### ISSUE TITLE
User profile

### ISSUE THREAD

**Issue by gberaudo** [c2corg/v6_api#92]
TODO:
- [ ] prevent indexing in Elastic search of content/summary for privacy.

**Comment by tsauerwein** [comment]
For the outings I would now need the user profile. The problem is that I can't create an association between an outing and a user, because `User` is not of type `Document`. I would propose the following:

 * Add a class `UserProfile` which inherits from `Document`.
 * `User.id` is a foreign-key of `Document.id`.
 * When creating a new user, an (empty) user profile document is created at the same time.

This allows to create associations between users and other documents.

Opinions?

**Comment by asaunier** [comment]
OK for me

**Comment by gberaudo** [comment]
That is roughly what was plan. +1

**Comment by tsauerwein** [comment]
Closing this one, because user-profiles are now implemented. When doing a search users are only included when authenticated.
